version: 2
jobs:
  build:
    working_directory: /dockerapp
    docker:
      - image: docker:17.05.0-ce-git
    parallelism: 2
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Install dependencies
          command: |
            apk add --no-cache py-pip=9.0.0-r1
            pip install docker-compose==1.15.0
      - run:
          name: Run tests
          command: |
            docker-compose up -d
            docker-compose run dockerapp python test.py
#  deploy:
#    working_directory: /dockerapp
#    docker:
#      - image: docker:17.05.0-ce-git
#        auth:
#          username: $DOCKER_HUB_USER_ID
#          password: $DOCKER_HUB_PWD
#    steps:
#      - checkout
      - run: |
            docker login -u=$DOCKER_HUB_USER_ID -p=$DOCKER_HUB_PWD
            docker tag dockerapp_dockerapp $DOCKER_HUB_USER_ID/dockerapp:$CIRCLE_SHA1
            docker tag dockerapp_dockerapp $DOCKER_HUB_USER_ID/dockerapp:latest
            docker push $DOCKER_HUB_USER_ID/dockerapp:$CIRCLE_SHA1
            docker push $DOCKER_HUB_USER_ID/dockerapp:latest
#          name: Publish application Docker image
#          commmand: |
#            docker login -e $DOCKER_HUB_EMAIL -u $DOCKER_HUB_USER_ID -p $DOCKER_HUB_PWD
#            docker tag dockerapp_dockerapp $DOCKER_HUB_USER_ID/dockerapp:$CIRCLE_SHA1
#            docker tag dockerapp_dockerapp $DOCKER_HUB_USER_ID/dockerapp:latest
#            docker push $DOCKER_HUB_USER_ID/dockerapp:$CIRCLE_SHA1
#            docker push $DOCKER_HUB_USER_ID/dockerapp:latest

#workflows:
#  version: 2
#  build-and-deploy:
#    jobs:
#      - build
#      - deploy:
#          requires:
#            - build
#          filters:
#            branches:
#              only: circle_ci_publish